---
- hosts: all
  become: true
  tasks:

    - name: update
      apt: update_cache=yes

    - name: Install Apache
      apt: name=apache state=latest


      notify:
        - restart apache

  handlers:
    - name: restart apache
      service: name=apache state=reloaded
...
