---
- hosts: all
  become: true
  tasks:

    - name: update
      apt: update_cache=yes

    - name: Install tomcat
      apt: name=tomcat state=latest


      notify:
        - restart tomcat

  handlers:
    - name: restart tomcat
      service: name=tomcat state=reloaded
...
